version: '2'

services:

  zambonigirl:
      image: 192.168.1.151:32000/zambonigirl:1.0.11
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
