version: '2'

services:

  zambonigirl:
      image: 192.168.1.84:32000/zambonigirl:1.0.6
      build:
          context: ./
          dockerfile: ./Dockerfile
      restart: unless-stopped
      ports:
          - "5001:443"
